require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'lib/**/*'

#####################################
#           Layouts                 #
#####################################

Layout/LineLength:
  Enabled: false

#####################################
#           Styles                  #
#####################################

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# コメントは強制しない
Style/Documentation:
  Enabled: false

# 空のメソッドはそのまま放置
Style/EmptyMethod:
  Enabled: false

# %w()や%i()表記は使用しない
Style/SymbolArray:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  
Style/RedundantSelf:
  Enabled: false

#####################################
#           Metrics                 #
#####################################

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

#####################################
#           Rails                   #
#####################################

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Presence:
  Enabled: false

Rails/Present:
  Enabled: false

Rails/Blank:
  Enabled: false
  
Rails/InverseOf:
  Enabled: false