version: '3'
services:
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    env_file:
      - ./environments/db.env
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mokumoku-app
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome

  db:
    image: mysql:5.7
    volumes:
      - mokumoku_data:/var/lib/mysql
    env_file:
      - ./environments/db.env
    ports:
      - 3306:3306

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

volumes:
  mokumoku_data:
